version: '3.8'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
        restart: always
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: p4ssw0rd
            MYSQL_DATABASE: db-natividad
            MYSQL_USER: zifher
            MYSQL_PASSWORD: secret1234